### ISSUE TITLE
Updates for the manual motor adjustments area

### ISSUE THREAD

**Issue by lwillmeth** [LBCC-SpaceClub/HAB2017#1]
Changing the range on the manual motor adjustments from 0-100 to 0-360 would let us easily visualize those values as degrees.  That would be great for manually moving the dish to specific angles during testing.

The text box is great, and would be even better if we could type values in there in addition to using the sliders.  That would be useful if we want a really specific angle like 36.71 degrees.

It might also be a good idea to label both sliders as azimuth and elevation.

![selection_019](https://cloud.githubusercontent.com/assets/5560088/26155659/cfd66e9a-3ac8-11e7-8083-5e9d10065746.png)

**Comment by proutyio** [comment]
Thanks for this input this was exactly what I was gonna ask if we needed.
 I will make these changes

**Comment by proutyio** [comment]
this is implemented, just need to do some input verification still

**Comment by proutyio** [comment]
Input validation working. Issue closed.
