### ISSUE TITLE
Need to create string for stepper arduino with payload location and gps checksum.

### ISSUE THREAD

**Issue by lwillmeth** [LBCC-SpaceClub/HAB2017#12]
It might be a pain.  [Here's a suggestion](http://code.activestate.com/recipes/576789-nmea-sentence-checksum/).

Another [useful link](http://www.gpsinformation.org/dale/nmea.htm#2.3) about NMEA strings.

And a [conversion calculator](http://www.directionsmag.com/site/latlong-converter/) to check your work.

**Comment by proutyio** [comment]
I will look into this.

**Comment by lwillmeth** [comment]
@proutyio I just pushed some code that probably solves this.  The tricky part was figuring out how to create the mandatory checksum for the string.

Right now I can send the stepper arduino a NMEA string with the payload location, and it spits back both tracker and payload locations, as well as the heading and distance between them.  So it's getting closer.

Issue #11 actually has a better list of tasks to get the steppers working, so I'll close this issue for now.
